name: dry-events
codacy_id: 3170162485134ea3b778c7e20e180b26
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica+oss@gmail.com"]
  summary: "Pub/sub system"
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [concurrent-ruby, "~> 1.0"]
    - [dry-core, "~> 1.0.0.rc1", "< 2"]
